### ISSUE TITLE
Minor HWL05 feedback

### ISSUE THREAD

**Issue by luciusmagn** [bieleluk/rust-developer#2]
https://github.com/bieleluk/rust-developer/blob/11df3e97caae32070308dc0df7f8c9898853b528/hw-l05-errors/src/main.rs#L18

It is fine in this case, but the Display of an Error may be several lines long, so it is the best to put it at the end of the line :)

https://github.com/bieleluk/rust-developer/blob/11df3e97caae32070308dc0df7f8c9898853b528/hw-l05-errors/src/str_utils.rs#L23

You should be able to just do `.map(Vec::len)`, it's a nice shortcut :)

Otherwise, a very nice solution!

**Comment by bieleluk** [comment]
Thank you for your feedback!

The solution to the inefficient `map` implementation had to be slightly different because `headers` is of `Vec<String>` type:
 `.map(String::len)`
